# Generated by Django 4.1.5 on 2023-02-03 18:27

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdata',
            name='data',
            field=models.JSONField(default=tracker.models.tracker_data_default, verbose_name='Tracker Data'),
        ),
    ]
