# Generated by Django 4.1.5 on 2023-02-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_trackerdata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerdata',
            name='title',
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='description',
            field=models.CharField(default='Description', max_length=500),
        ),
    ]
