# Generated by Django 4.1.6 on 2023-03-11 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_trackerdata_title_trackerdata_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerdata',
            name='data',
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='compost',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='donations',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='farmers',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='gardens',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='landfill',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='other',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackerdata',
            name='partners',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackerdata',
            name='description',
            field=models.CharField(default='Description', max_length=150),
        ),
    ]
