# Generated by Django 4.1.6 on 2023-03-15 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_trackerdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 2, 47, 59, 981241, tzinfo=datetime.timezone.utc)),
        ),
    ]
