# Generated by Django 4.1.6 on 2023-03-30 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_trackerdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 40, 4, 945015, tzinfo=datetime.timezone.utc)),
        ),
    ]
